version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Runtime python Successful"
  build:
    commands:
      - echo "Zipping deployment package......"
      - zip producer_deployment_package.zip producer_lambda_function.py
  post_build:
    commands:
      - echo "Uploading to S3...."
      - aws s3 cp producer_deployment_package.zip s3://lambda-builds-zips/
      - echo "Updating Producer Lambda function via S3......"
      - aws lambda update-function-code --function-name ProduceAirbnbBookingData --s3-bucket lambda-builds-zips --s3-key producer_deployment_package.zip
      - echo "Deployment Complete!"